"""Repository rule to detect the number of available GPUs at build time.

This rule runs at `bazel build/test` invocation (during the loading/analysis
phase) and generates a `defs.bzl` file containing `GPU_COUNT`, which can be
loaded by BUILD files to set `shard_count` dynamically.

Usage in WORKSPACE:
    load("//build_tools:gpu_count_configure.bzl", "gpu_count_configure")
    gpu_count_configure(name = "local_gpu_config")

Usage in BUILD files:
    load("@local_gpu_config//:defs.bzl", "GPU_COUNT")
    xla_test(
        name = "iota_test",
        srcs = ["iota_test.cc"],
        shard_count = GPU_COUNT,
        ...
    )

Override via environment variable (useful in CI or when auto-detection fails):
    XLA_GPU_SHARD_COUNT=8 bazel test //xla/tests:iota_test_rocm
"""

def _gpu_count_configure_impl(repository_ctx):
    """Detects the number of available GPUs and generates defs.bzl."""

    gpu_count = 0
    detection_source = "none"

    # Allow explicit override via environment variable (highest priority).
    override = repository_ctx.os.environ.get("XLA_GPU_SHARD_COUNT", "")
    if override.isdigit() and int(override) > 0:
        gpu_count = int(override)
        detection_source = "XLA_GPU_SHARD_COUNT env var"
        print("[gpu_count_configure] Override via XLA_GPU_SHARD_COUNT=%s" % override)

    # Try ROCm (AMD GPUs) via rocm-smi.
    # Use grep -oP to extract unique GPU indices, then count them.
    # This avoids over-counting when --showid prints multiple lines per GPU.
    if gpu_count == 0:
        result = repository_ctx.execute(
            ["bash", "-c",
             "rocm-smi --showid 2>/dev/null | grep -oP 'GPU\\[\\K[0-9]+' | sort -u | wc -l"],
        )
        print("[gpu_count_configure] rocm-smi return_code=%d stdout=%r stderr=%r" % (
            result.return_code, result.stdout, result.stderr))
        if result.return_code == 0:
            stripped = result.stdout.strip()
            if stripped.isdigit() and int(stripped) > 0:
                gpu_count = int(stripped)
                detection_source = "rocm-smi"

    # Try NVIDIA GPUs via nvidia-smi.
    if gpu_count == 0:
        result = repository_ctx.execute(
            ["bash", "-c",
             "nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | grep -c ."],
        )
        print("[gpu_count_configure] nvidia-smi return_code=%d stdout=%r stderr=%r" % (
            result.return_code, result.stdout, result.stderr))
        if result.return_code == 0:
            stripped = result.stdout.strip()
            if stripped.isdigit() and int(stripped) > 0:
                gpu_count = int(stripped)
                detection_source = "nvidia-smi"

    # Try counting /dev/dri/renderD* device nodes as a last resort.
    if gpu_count == 0:
        result = repository_ctx.execute(
            ["bash", "-c", "ls /dev/dri/renderD* 2>/dev/null | wc -l"],
        )
        print("[gpu_count_configure] /dev/dri/renderD* return_code=%d stdout=%r stderr=%r" % (
            result.return_code, result.stdout, result.stderr))
        if result.return_code == 0:
            stripped = result.stdout.strip()
            if stripped.isdigit() and int(stripped) > 0:
                gpu_count = int(stripped)
                detection_source = "/dev/dri/renderD*"

    # Default to 8 shards if no GPU was detected (a standard 8-GPU node).
    # This preserves reasonable parallelism on build hosts where
    # rocm-smi/nvidia-smi are not available.
    if gpu_count <= 0:
        gpu_count = 8
        detection_source = "default"

    print("[gpu_count_configure] GPU_COUNT=%d (source: %s)" % (gpu_count, detection_source))

    repository_ctx.file("BUILD.bazel", "# Auto-generated by gpu_count_configure\n")
    repository_ctx.file(
        "defs.bzl",
        content = """\
# Auto-generated by //build_tools:gpu_count_configure.bzl
# Detected GPU count: {gpu_count}
#
# To override, set XLA_GPU_SHARD_COUNT=<n> before invoking bazel.
GPU_COUNT = {gpu_count}
""".format(gpu_count = gpu_count),
    )

gpu_count_configure = repository_rule(
    implementation = _gpu_count_configure_impl,
    # Mark as local so Bazel does not cache the result across machines and
    # re-evaluates whenever the relevant environment variables change.
    local = True,
    environ = [
        # ROCm / HIP
        "ROCM_PATH",
        "HIP_PATH",
        "HIP_VISIBLE_DEVICES",
        "ROCR_VISIBLE_DEVICES",
        # CUDA / NVIDIA
        "CUDA_HOME",
        "CUDA_VISIBLE_DEVICES",
        # Manual override
        "XLA_GPU_SHARD_COUNT",
    ],
    doc = """\
Detects the number of available GPUs on the build/test host and exposes
the count as `GPU_COUNT` in `@local_gpu_config//:defs.bzl`.

Supports ROCm (via rocm-smi) and NVIDIA (via nvidia-smi), with a
/dev/dri/renderD* fallback. The count can be overridden by setting the
`XLA_GPU_SHARD_COUNT` environment variable.
""",
)
