filegroup(
    name = "rbe-cert.crt",
    srcs = ["ci-cert.crt"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "rbe-cert.key",
    srcs = ["ci-cert.key"],
    visibility = ["//visibility:public"],
)
