name: Internal CI

# Runs CI checks on pull requests targeting this branch.

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-check:
    uses: ROCm/xla/.github/workflows/rocm_xla_ci.yml@rocm-dev-infra
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      concurrency_group: ${{ format('CI ROCm-PR-{0}', github.event.pull_request.number) }}
    secrets: inherit

