# Copyright 2026 The OpenXLA Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

name: CI ROCm Sanitizers

permissions:
  contents: read

on:
  pull_request_target:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  execute-xla-ut-sanitizers:
    # Only run if the "sanitizers" label was added
    if: github.event.label.name == 'sanitizers'
    runs-on: linux-mi250-4
    strategy:
      fail-fast: false
      matrix:
        mode:
          - {name: "asan", configs: ["--config=rocm_ci", "--config=asan"]}
          - {name: "tsan", configs: ["--config=rocm_ci", "--config=tsan"]}
    container:
      # set in https://github.com/ROCm/xla/settings/variables/actions
      image: ${{ vars.DOCKER_IMAGE }}
      options: >-
        --device=/dev/dri
        --device=/dev/kfd
        --shm-size=16G
        --cap-add=SYS_PTRACE
        --security-opt=seccomp=unconfined
      volumes:
        - /tmp/bazel-cache:/root/.cache/bazel
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Fetch execute_ci_build.sh from rocm-dev-infram
        run: |
          wget -O build_tools/rocm/execute_ci_build.sh https://raw.githubusercontent.com/ROCm/xla/refs/heads/rocm-dev-infra/build_tools/rocm/execute_ci_build.sh
          chmod +x build_tools/rocm/execute_ci_build.sh

      - name: Get RBE cluster keys
        env:
          RBE_CI_CERT: ${{ secrets.RBE_CI_CERT }}
          RBE_CI_KEY: ${{ secrets.RBE_CI_KEY }}
        run: |
          mkdir -p /tf/certificates
          echo "$RBE_CI_CERT" > /tf/certificates/ci-cert.crt
          echo "$RBE_CI_KEY" > /tf/certificates/ci-cert.key

      - name: CPU Info
        run: lscpu

      - name: ROCm info
        run: /opt/rocm/bin/rocminfo

      - name: Test XLA [${{ matrix.mode.name }}] [single_gpu]
        run: |
          build_tools/rocm/execute_ci_build.sh \
            ${{ join(matrix.mode.configs, ' ') }} \
            --config=ci_single_gpu \
            --local_test_jobs=4 \
            --strategy=TestRunner=local \
            --repo_env=TF_ROCM_AMDGPU_TARGETS=gfx90a,gfx942 \
            --repo_env=TF_ROCM_RBE_DOCKER_IMAGE=${{ vars.DOCKER_IMAGE }} \
            --config=xla_sgpu

      - name: Test XLA [${{ matrix.mode.name }}] [multi_gpu]
        if: always() && !cancelled()
        run: |
          build_tools/rocm/execute_ci_build.sh \
            ${{ join(matrix.mode.configs, ' ') }} \
            --config=ci_multi_gpu \
            --local_test_jobs=1 \
            --strategy=TestRunner=local \
            --repo_env=TF_ROCM_AMDGPU_TARGETS=gfx90a,gfx942 \
            --repo_env=TF_ROCM_RBE_DOCKER_IMAGE=${{ vars.DOCKER_IMAGE }} \
            --config=xla_mgpu
