# Pulls the latest changes from upstream into main and opens a PR to merge
# them into rocm-main branch.

name: ROCm Nightly Upstream Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'
permissions:
  contents: write
  pull-requests: write
env:
  SYNC_BRANCH_NAME: ci-upstream-sync-${{ github.run_number }}_${{ github.run_attempt }}
jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh auth status
          gh repo sync rocm/xla -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-sync-branch:
    needs: sync-main
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Create branch
        run: |
          git fetch origin
          git checkout -b $SYNC_BRANCH_NAME origin/main
          # Try and merge rocm-main into this new branch so that we don't run upstream's CI code
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          if git merge origin/rocm-main --ff-only; then
            echo "Merged rocm-main into CI branch"
            echo "merged=1" >> "$GITHUB_OUTPUT"
          else
            echo "merged=0" >> "$GITHUB_OUTPUT"
          fi
          git push origin HEAD:refs/heads/$SYNC_BRANCH_NAME
  open-sync-pr:
    needs: create-sync-branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --repo $GITHUB_REPOSITORY --head $SYNC_BRANCH_NAME --base rocm-main --title "CI: $(date +%x) upstream sync" --body "Daily sync with upstream"
          gh pr merge --repo $GITHUB_REPOSITORY --merge --auto $SYNC_BRANCH_NAME
          # If the merge failed, leave a comment on the PR telling devs how to fix it
          if [[ $MERGED == 0 ]]; then
            gh pr comment --repo $GITHUB_REPOSITORY --body "Merging of this branch with rocm-main has failed and must be resolved by a dev. In your local repo, please run git fetch origin; git checkout $SYNC_BRANCH_NAME; git merge rocm-main` and then git push origin $SYNC_BRANCH_MAIN once any conflicts have been resolved."
          fi
        env:
          MERGED: ${{ needs.create-sync-branch.outputs.merged }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

